apiVersion: v1
kind: ConfigMap
data:
  nginx.conf: |
    events {
    }

    http {
      server {
        listen 8000;
        root /data/www;
        location / {
          try_files '' /redirect.html =404;
        }
      }
    }
  redirect.html: |
    <head>
      <meta http-equiv="Refresh" content="0; URL=https://vmware.zoom.us/j/95020320288">
    </head>
    <body>
      <a href="https://vmware.zoom.us/j/95020320288">https://vmware.zoom.us/j/95020320288</a>
    </body>
metadata:
  name: nginx-conf
