postgresql:
  enabled: false

concourse:
  image: concourse/concourse
  imageDigest: sha256:b50f6207373cc671965ea0c4832bb394508b7eca337a80100d38d961be27fbb5

  postgresql:
    enabled: false

  persistence:
    worker:
      storageClass: ssd
      size: 750Gi

  web:
    enabled: false

  worker:
    replicas: 20
    annotations:
      manual-update-revision: "1"
    terminationGracePeriodSeconds: 3600
    livenessProbe:
      periodSeconds: 60
      failureThreshold: 10
      timeoutSeconds: 45
    nodeSelector: { cloud.google.com/gke-nodepool: workers-3 }
    hardAntiAffinity: true
    env:
    - name: CONCOURSE_GARDEN_NETWORK_POOL
      value: "10.254.0.0/16"
    - name: CONCOURSE_GARDEN_MAX_CONTAINERS
      value: "500"
    - name: CONCOURSE_GARDEN_DENY_NETWORK
      value: "169.254.169.254/32"
    resources:
      limits:   { cpu: 7500m, memory: 14Gi }
      requests: { cpu: 0m,    memory: 0Gi  }

  concourse:
    worker:
      rebalanceInterval: 2h
      baggageclaim: { driver: overlay }
      healthcheckTimeout: 40s
      tsa:
        hosts: ['hush-house-web.hush-house.svc.cluster.local:2222']

  secrets:
    hostKeyPub: |-
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMU5L98yRnMsQosvfeeC/5qEUy9P13RdO88FLRYTNZIDX7GVW4NRcVqEcysNckoGYPVPeX19I03EXeO4yf71in4F4u9JV+SZaefyeG/6Q9fAO5HbdTdooRPm9yaydDHSwVKx1yPkhm/HIqNvwSBbqipLhjq3zPKCXKDMKYWoPQf/OeERHmW9sTbfbvB1mgKVUGtU8Eox787k8FG/Gq17iHPwxQd8tzsaa/zgUTbjHuOMhSrm8hgL0GYPn8OaS+2Y/FfCiLZWZVeTmLv11F26r1G8I7SSs5+qfn5ZUz3ZfjRcuv077VkeyCVGtxKcjSubMe6HfmmSx0TkwcKjA4vqWh pivotal@DX187.local
