apiVersion: v1
kind: Secret
metadata:
  name: vault-server-tls
type: Opaque
data:
  {{- if not .Values.vault.global.tlsDisable  }}
  vault.ca: {{ default "" .Values.vault.ca  | b64enc | quote }}
  vault.crt: {{ default "" .Values.vault.crt | b64enc | quote }}
  vault.key: {{ default "" .Values.vault.key | b64enc | quote }}
  {{- end }}
  vault.ip: {{ default "" .Values.vault.ip | b64enc | quote }}
  vault.secret: {{ default "" .Values.vault.secret | b64enc | quote }}
