# fly -t ci set-team -n contributor --config contributor-team-config.yml
roles:
- name: owner
  github:
    teams: ["concourse:pivotal"]
- name: pipeline-operator
  github:
    teams: ["concourse:contributors"]
