dependencies:
- name: concourse
  repository: https://concourse-charts.storage.googleapis.com/
  version: 11.1.0
- name: datadog
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 1.39.5
