dependencies:
- name: concourse
  repository: file:///home/ubuntu/workspace/concourse-chart
  version: 10.1.0
- name: datadog
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 1.39.5
