dependencies:
- name: concourse
  repository: file:///Users/ruiyang/workspace/concourse-chart
  version: 10.2.3
- name: datadog
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 1.39.5
