apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: concourse@pivotal.io
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production-acct-key
    solvers:
      - dns01:
          clouddns:
            project: cf-concourse-production
            serviceAccountSecretRef:
              name: clouddns-dns01-solver-svc-acct
              key: key.json
