apiVersion: v1
kind: Service
metadata:
  name: cadet
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"cadet-backendconfig"}}'

    # i'm not sure why we're still "beta", but eventually this can be removed
    beta.cloud.google.com/backend-config: '{"ports": {"80":"cadet-backendconfig"}}'
spec:
  type: NodePort
  selector:
    app: cadet
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
