apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-config
  labels:
    app: otelcol-config
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  otelcol.yml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:55680
    exporters:
      jaeger:
        endpoint: localhost:14250
        insecure: true
      logging:
        loglevel: debug
    processors:
      attributes/strip_tags:
        actions:
        - key: telemetry.sdk.name
          action: delete
        - key: telemetry.sdk.language
          action: delete
        - key: instrumentation.name
          action: delete
      attributes/insert_tags:
        actions:
        - key: cluster
          action: insert
          value: ci.concourse-ci.org
        # uncomment to disable "intelligent" sampling by wavefront
        # - key: debug
        #   action: insert
        #   value: "true"
    service:
      pipelines:
        traces:
          receivers:
          - otlp
          processors:
          - attributes/strip_tags
          - attributes/insert_tags
          exporters:
          - jaeger
